server:
  port: 9527
spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      # http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

#info配置 http://xxxx/actuator/info 访问信息
info:
  app.name: spring-cloud-zuul #项目的名称
  company.name: com.yan #公司的名称
  d: 1.2

# 网关配置
zuul:
  routes:
    # 网关对应的工程
    mydept.serviceId: provider-dept-hystrix
    # 更换成的路由名
    mydept.path: /app/**
    ignored-services: "*"  # 不能再使用某个(*：全部)路径访问了，ignored ： 忽略,隐藏全部的~，必须走网关
    # prefix: /kuagn # 设置公共的前缀,实现隐藏原有路由


#    如果多个服务需要经过路由，则同 povider-product方式继续添加，例如：
#    provider-product:    # 路由名称，名称任意，路由名称唯一
#      path: /product/** # 访问路径
#      serviceId: microservice-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
#      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1